[package]
name = "rong_bot_prime"
version = "0.0.1"
authors = ["ForeverAnApple"]
edition = "2021"

[dependencies.serenity]
version = "0.10.9"
features = ["framework", "standard_framework", "client", "gateway", "rustls_backend", "model"]

[dependencies.tokio]
version = "1.15"
features = ["macros", "rt-multi-thread"]