[package]
name = "RongPrime"
version = "0.0.1"
authors = ["ForeverAnApple"]
edition = "2021"

[dependencies]
serenity = { default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }