---
name: Docker build and push to registry

on:
  push:
    branches:
      - 'prod'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to TheBell Registry
        uses: docker/login-action@v2
        with:
          registry: registry.thebell.dev
          username: ${{ secrets.REG_ROBOT_NAME }}
          password: ${{ secrets.REG_ROBOT_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.thebell.dev/rong/rongbotprime:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
